import type { CoinConfig, CoinId } from '../types/coins';

export const COINS: Record<CoinId, CoinConfig> = {
  bitcoin: {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    color: '#F7931A',
    flag: 'BTC',
    type: 'crypto',
    geckoId: 'bitcoin',
  },
  zcash: {
    id: 'zcash',
    name: 'Zcash',
    symbol: 'ZEC',
    color: '#ECB244',
    flag: 'ZEC',
    type: 'crypto',
    geckoId: 'zcash',
  },
  usoil: {
    id: 'usoil',
    name: 'Crude Oil',
    symbol: 'USOIL',
    color: '#a0522d',
    flag: 'OIL',
    type: 'stock',
    yahooSymbol: 'CL=F',
  },
  sp500: {
    id: 'sp500',
    name: 'S&P 500',
    symbol: 'SPX',
    color: '#4fc3f7',
    flag: 'US',
    type: 'stock',
    yahooSymbol: '^GSPC',
  },
  nasdaq100: {
    id: 'nasdaq100',
    name: 'NASDAQ-100',
    symbol: 'NDX',
    color: '#e040fb',
    flag: 'US',
    type: 'stock',
    yahooSymbol: '^NDX',
  },
  csi300: {
    id: 'csi300',
    name: 'CSI 300',
    symbol: 'CSI',
    color: '#ff5252',
    flag: 'CN',
    type: 'stock',
    yahooSymbol: '000300.SS',
  },
  nikkei225: {
    id: 'nikkei225',
    name: 'Nikkei 225',
    symbol: 'N225',
    color: '#69f0ae',
    flag: 'JP',
    type: 'stock',
    yahooSymbol: '^N225',
  },
  euronext100: {
    id: 'euronext100',
    name: 'Euronext 100',
    symbol: 'N100',
    color: '#b388ff',
    flag: 'EU',
    type: 'stock',
    yahooSymbol: '^N100',
  },
  ftse100: {
    id: 'ftse100',
    name: 'FTSE 100',
    symbol: 'FTSE',
    color: '#26c6da',
    flag: 'GB',
    type: 'stock',
    yahooSymbol: '^FTSE',
  },
};

export const COIN_LIST: CoinId[] = ['bitcoin', 'zcash', 'usoil', 'sp500', 'nasdaq100', 'csi300', 'nikkei225', 'euronext100', 'ftse100'];
